<#
.Description
    An empty site is generally not recommended. The term describes a site without any Domain Controllers.
    A site of this sort has two possible reasons for existing – Microsoft SCCM product used for software
    distribution and other management tools to help identify something in Active directory for end users
    or application use. In general this isn’t an issue, but if they are not needed, removing them is a
    good practice. Less for Active directory to replicated to existing Domain Controllers in other sites.
#>

$DomainControllers = (Get-ADDomainController -Filter *).Name
Foreach ($DomainController in $DomainControllers) {
    # Set up variables for the loop:
    $Query = $True
    $AutoGenerated = $Null

    # Get a list of links for this Domain Controller:
    Try {
        $Links = Get-ADReplicationConnection -Server $DomainController -ErrorAction STOP
    } Catch {
        Write-host 'Failed - Unable to query links.' -ForegroundColor Red
        $Query = $False
    }

    # Check each set of links to analyze the ones for each Domain Controller:
    If ($Query) {
        Foreach ($Line in $Links) {
            # Fix Values
            $Name = $Line.Name
            $Autogenerated= $Line.Autogenerated
            $ReplicateFromDirectoryServer = $Line.ReplicateFromDirectoryServer
            $ReplicateToDirectoryServer = $Line.ReplicateToDirectoryServer
            $FromLarge = $ReplicateFromDirectoryServer.Split(',')[1]
            $ToLarge = $ReplicateToDirectoryServer.Split(',')[0]
            $FinalFrom = $FromLarge.Split('=')[1]
            $FinalTo = $ToLarge.Split('=')[1]
            $SiteLarge = $Line.DistinguishedName.Split(',')[4]
            $Site = $SiteLarge.Split('=')[1]
            $Row = "$DomainController,$Site,$Name,$Autogenerated,$FinalFrom,$FinalTo" | Out-File $ADReplicationConnectionDestination -Append
        }
    } Else {
        Write-host '  Domain Controller with no Links found - ' -ForegroundColor White -NoNewline
        Write-Host "$DomainController" -ForegroundColor Yellow -NoNewline
        Write-Host ' - is this Domain Controller needed?' -ForegroundColor White
        $Row = "$DomainController,NoLink,,,," | Out-File $ADReplicationConnectionDestination -Append
    }
}


# SIG # Begin signature block
# MIIFuAYJKoZIhvcNAQcCoIIFqTCCBaUCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUGX0fFOA6g0AZaMyNNiRE9Hkz
# WuWgggM6MIIDNjCCAh6gAwIBAgIQeugH5LewQKBKT6dPXhQ7sDANBgkqhkiG9w0B
# AQUFADAzMTEwLwYDVQQDDChQb1NoLUVhc3lXaW4gQnkgRGFuIEtvbW5pY2sgKGhp
# Z2gxMDFicm8pMB4XDTIxMTIxNDA1MDIwMFoXDTMxMTIxNDA1MTIwMFowMzExMC8G
# A1UEAwwoUG9TaC1FYXN5V2luIEJ5IERhbiBLb21uaWNrIChoaWdoMTAxYnJvKTCC
# ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALvIxUDFEVGB/G0FXPryoNlF
# dA65j5jPEFM2R4468rjlTVsNYUOR+XvhjmhpggSQa6SzvXtklUJIJ6LgVUpt/0C1
# zlr1pRwTvsd3svI7FHTbJahijICjCv8u+bFcAR2hH3oHFZTqvzWD1yG9FGCw2pq3
# h4ahxtYBd1+/n+jOtPUoMzcKIOXCUe4Cay+xP8k0/OLIVvKYRlMY4B9hvTW2CK7N
# fPnvFpNFeGgZKPRLESlaWncbtEBkexmnWuferJsRtjqC75uNYuTimLDSXvNps3dJ
# wkIvKS1NcxfTqQArX3Sg5qKX+ZR21uugKXLUyMqXmVo2VEyYJLAAAITEBDM8ngUC
# AwEAAaNGMEQwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMDMB0G
# A1UdDgQWBBSDJIlo6BcZ7KJAW5hoB/aaTLxFzTANBgkqhkiG9w0BAQUFAAOCAQEA
# ouCzal7zPn9vc/C9uq7IDNb1oNbWbVlGJELLQQYdfBE9NWmXi7RfYNd8mdCLt9kF
# CBP/ZjHKianHeZiYay1Tj+4H541iUN9bPZ/EaEIup8nTzPbJcmDbaAGaFt2PFG4U
# 3YwiiFgxFlyGzrp//sVnOdtEtiOsS7uK9NexZ3eEQfb/Cd9HRikeUG8ZR5VoQ/kH
# 2t2+tYoCP4HsyOkEeSQbnxlO9s1jlSNvqv4aygv0L6l7zufiKcuG7q4xv/5OvZ+d
# TcY0W3MVlrrNp1T2wxzl3Q6DgI+zuaaA1w4ZGHyxP8PLr6lMi6hIugI1BSYVfk8h
# 7KAaul5m+zUTDBUyNd91ojGCAegwggHkAgEBMEcwMzExMC8GA1UEAwwoUG9TaC1F
# YXN5V2luIEJ5IERhbiBLb21uaWNrIChoaWdoMTAxYnJvKQIQeugH5LewQKBKT6dP
# XhQ7sDAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkq
# hkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGC
# NwIBFTAjBgkqhkiG9w0BCQQxFgQUfmXHc8gBq9K/J1jAyf6GtgfORogwDQYJKoZI
# hvcNAQEBBQAEggEAuzCOdh/62EISgCmgoByp3VH//SHY6G+8CyrAWCqjiGziFL/c
# PpI7y6Z6KkZFld2g3wg9bJobwJz89BZumoUNt+nIq2A2MPihzeJ/T0RugUwdszXd
# OZ9JdRvaudaLoc8bz8xN9Dt5IikmySn7Z9fwBD8w+S8ewV9FybUVIiTU5bvC10Hp
# 5iFJTGUO5X0FYA97fDSJZwRePdXO5Rsqsjz9IBG7XTkuR5gp9w9l4ZlUPq/Zc0TH
# fsEon5f43aY3DMeVyHgbf19Vs2vsuRqRp1alXMkcEevs0Op47njcF+vJkZGq8H3i
# IMO7CVCy6NWcgL6o37kFSbx4V57S2isq7FOZCw==
# SIG # End signature block
